name: Create Repo from Template
on:
  workflow_dispatch:

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Run Script
        run: node ./scripts/createRepo.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
